title: Urban Tech Garden
email: contact@urbantechgarden.com
description: >-
  Urban gardening for mere mortals. Frugal organic gardening, DIY tech,
  instrumentation, and urban food growing.
baseurl: ""
url: "http://urbantechgarden.com"
instagram_username: urbantechgarden
show_excerpts: true
excerpt_separator: <!--more-->
google_analytics: UA-44633314-4
disqus:
  shortname: urbantechgarden-com

safe: true
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

header_pages:
  - recommends.md
  - contact.md
  - about.md
